insert into CURSO (expediente, nombre) values (1, 'Matemáticas 1');
insert into CURSO (expediente, nombre) values (2, 'Literatura 1');
insert into CURSO (expediente, nombre) values (3, 'Ciencias 1');
insert into CURSO (expediente, nombre) values (4, 'Historia 1');
insert into CURSO (expediente, nombre) values (5, 'Inglés 1');
insert into CURSO (expediente, nombre) values (6, 'Educación Física 1');
insert into CURSO (expediente, nombre) values (7, 'Educación Artística 1');
insert into CURSO (expediente, nombre) values (8, 'Tecnología 1');
insert into CURSO (expediente, nombre) values (9, 'Educación Ciudadana 1');
insert into CURSO (expediente, nombre) values (10, 'Lenguaje 1');
insert into CURSO (expediente, nombre) values (11, 'Matemáticas 2');
insert into CURSO (expediente, nombre) values (12, 'Literatura 2');
insert into CURSO (expediente, nombre) values (13, 'Ciencias 2');
insert into CURSO (expediente, nombre) values (14, 'Historia 2');
insert into CURSO (expediente, nombre) values (15, 'Inglés 2');
insert into CURSO (expediente, nombre) values (16, 'Educación Física 2');
insert into CURSO (expediente, nombre) values (17, 'Educación Artística 2');
insert into CURSO (expediente, nombre) values (18, 'Tecnología 2');
insert into CURSO (expediente, nombre) values (19, 'Educación Ciudadana 2');
insert into CURSO (expediente, nombre) values (20, 'Lenguaje 2');
insert into CURSO (expediente, nombre) values (21, 'Matemáticas 3');
insert into CURSO (expediente, nombre) values (22, 'Literatura 3');
insert into CURSO (expediente, nombre) values (23, 'Ciencias 3');
insert into CURSO (expediente, nombre) values (24, 'Historia 3');
insert into CURSO (expediente, nombre) values (25, 'Inglés 3');
insert into CURSO (expediente, nombre) values (26, 'Educación Física 3');
insert into CURSO (expediente, nombre) values (27, 'Educación Artística 3');
insert into CURSO (expediente, nombre) values (28, 'Tecnología 3');
insert into CURSO (expediente, nombre) values (29, 'Educación Ciudadana 3');
insert into CURSO (expediente, nombre) values (30, 'Lenguaje 3');
insert into CURSO (expediente, nombre) values (31, 'Matemáticas 4');
insert into CURSO (expediente, nombre) values (32, 'Literatura 4');
insert into CURSO (expediente, nombre) values (33, 'Ciencias 4);
insert into CURSO (expediente, nombre) values (34, 'Historia 4');
insert into CURSO (expediente, nombre) values (35, 'Inglés 4');
insert into CURSO (expediente, nombre) values (36, 'Educación Física 4');
insert into CURSO (expediente, nombre) values (37, 'Educación Artística 4');
insert into CURSO (expediente, nombre) values (38, 'Tecnología 4');
insert into CURSO (expediente, nombre) values (39, 'Educación Ciudadana 4');
insert into CURSO (expediente, nombre) values (40, 'Lenguaje 4');
insert into CURSO (expediente, nombre) values (41, 'Matemáticas 5');
insert into CURSO (expediente, nombre) values (42, 'Literatura 5');
insert into CURSO (expediente, nombre) values (43, 'Ciencias 5');
insert into CURSO (expediente, nombre) values (44, 'Historia 5');
insert into CURSO (expediente, nombre) values (45, 'Inglés 5');
insert into CURSO (expediente, nombre) values (46, 'Educación Física 5');
insert into CURSO (expediente, nombre) values (47, 'Educación Artística 5');
insert into CURSO (expediente, nombre) values (48, 'Tecnología 5');
insert into CURSO (expediente, nombre) values (49, 'Educación Ciudadana 5');
insert into CURSO (expediente, nombre) values (50, 'Lenguaje 5');
insert into CURSO (expediente, nombre) values (51, 'Matemáticas 6');
insert into CURSO (expediente, nombre) values (52, 'Literatura 6');
insert into CURSO (expediente, nombre) values (53, 'Ciencias 6');
insert into CURSO (expediente, nombre) values (54, 'Historia 6');
insert into CURSO (expediente, nombre) values (55, 'Inglés 6');
insert into CURSO (expediente, nombre) values (56, 'Educación Física 6');
insert into CURSO (expediente, nombre) values (57, 'Educación Artística 6');
insert into CURSO (expediente, nombre) values (58, 'Tecnología 6');
insert into CURSO (expediente, nombre) values (59, 'Educación Ciudadana 6');
insert into CURSO (expediente, nombre) values (60, 'Lenguaje 6');
insert into CURSO (expediente, nombre) values (61, 'Matemáticas 7');
insert into CURSO (expediente, nombre) values (62, 'Literatura 7');
insert into CURSO (expediente, nombre) values (63, 'Ciencias 7');
insert into CURSO (expediente, nombre) values (64, 'Historia 7');
insert into CURSO (expediente, nombre) values (65, 'Inglés 7');
insert into CURSO (expediente, nombre) values (66, 'Educación Física 7');
insert into CURSO (expediente, nombre) values (67, 'Educación Artística 7');
insert into CURSO (expediente, nombre) values (68, 'Tecnología 7');
insert into CURSO (expediente, nombre) values (69, 'Educación Ciudadana 7');
insert into CURSO (expediente, nombre) values (70, 'Lenguaje 7');
insert into CURSO (expediente, nombre) values (71, 'Matemáticas 8');
insert into CURSO (expediente, nombre) values (72, 'Literatura 8');
insert into CURSO (expediente, nombre) values (73, 'Ciencias 8');
insert into CURSO (expediente, nombre) values (74, 'Historia 8');
insert into CURSO (expediente, nombre) values (75, 'Inglés 8');
insert into CURSO (expediente, nombre) values (76, 'Educación Física 8');
insert into CURSO (expediente, nombre) values (77, 'Educación Artística 8');
insert into CURSO (expediente, nombre) values (78, 'Tecnología 8');
insert into CURSO (expediente, nombre) values (79, 'Educación Ciudadana 8');
insert into CURSO (expediente, nombre) values (80, 'Lenguaje 8');
insert into CURSO (expediente, nombre) values (81, 'Matemáticas 9');
insert into CURSO (expediente, nombre) values (82, 'Literatura 9');
insert into CURSO (expediente, nombre) values (83, 'Ciencias 9');
insert into CURSO (expediente, nombre) values (84, 'Historia 9');
insert into CURSO (expediente, nombre) values (85, 'Inglés 9');
insert into CURSO (expediente, nombre) values (86, 'Educación Física 9');
insert into CURSO (expediente, nombre) values (87, 'Educación Artística 9');
insert into CURSO (expediente, nombre) values (88, 'Tecnología 9');
insert into CURSO (expediente, nombre) values (89, 'Educación Ciudadana 9');
insert into CURSO (expediente, nombre) values (90, 'Lenguaje 9');
insert into CURSO (expediente, nombre) values (91, 'Matemáticas 10');
insert into CURSO (expediente, nombre) values (92, 'Literatura 10');
insert into CURSO (expediente, nombre) values (93, 'Ciencias 10');
insert into CURSO (expediente, nombre) values (94, 'Historia 10');
insert into CURSO (expediente, nombre) values (95, 'Inglés 10');
insert into CURSO (expediente, nombre) values (96, 'Educación Física 10');
insert into CURSO (expediente, nombre) values (97, 'Educación Artística 10');
insert into CURSO (expediente, nombre) values (98, 'Tecnología 10');
insert into CURSO (expediente, nombre) values (99, 'Educación Ciudadana 10');
insert into CURSO (expediente, nombre) values (100, 'Lenguaje 10');
