insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (1, 'Tecnología', 'yqigpcpjcs', 1, 1);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (2, 'Inglés', 'sryxmipiiz', 2, 2);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (3, 'Educación Ciudadana', 'fpyieayhdb', 3, 3);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (4, 'Tecnología', 'dpoushvpab', 4, 4);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (5, 'Educación Física', 'uyaaidkeul', 5, 5);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (6, 'Tecnología', 'xxqgiqlryh', 6, 6);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (7, 'Historia', 'aclvicjvvp', 7, 7);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (8, 'Ciencias', 'uewdsxleki', 8, 8);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (9, 'Educación Ciudadana', 'bbpbtntcaj', 9, 9);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (10, 'Educación Ciudadana', 'wgmjpxushg', 10, 10);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (11, 'Historia', 'diraolluxl', 11, 11);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (12, 'Educación Física', 'tncwhqhskz', 12, 12);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (13, 'Matemáticas', 'ptttnueyht', 13, 13);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (14, 'Matemáticas', 'xfvsotyfcj', 14, 14);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (15, 'Educación Artística', 'agkfhltphw', 15, 15);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (16, 'Historia', 'nuhgvluxxa', 16, 16);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (17, 'Tecnología', 'sujskytfjd', 17, 17);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (18, 'Inglés', 'sletjihzeo', 18, 18);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (19, 'Literatura', 'qgijyondbq', 19, 19);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (20, 'Lenguaje', 'agpndvapri', 20, 20);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (21, 'Educación Ciudadana', 'otyajljiwr', 21, 21);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (22, 'Educación Física', 'elsowfhwqi', 22, 22);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (23, 'Tecnología', 'temxskpkax', 23, 23);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (24, 'Ciencias', 'zmzqlzisbp', 24, 24);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (25, 'Ciencias', 'rknukqvrzr', 25, 25);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (26, 'Historia', 'fccwucdnoj', 26, 26);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (27, 'Educación Ciudadana', 'fiwsxaoumb', 27, 27);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (28, 'Literatura', 'dribgjtlsu', 28, 28);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (29, 'Educación Física', 'eftqyczaig', 29, 29);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (30, 'Educación Artística', 'kfcllwxmyd', 30, 30);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (31, 'Matemáticas', 'qkpsareowk', 31, 31);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (32, 'Educación Ciudadana', 'iixwaanhjd', 32, 32);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (33, 'Educación Ciudadana', 'etzxyeqxez', 33, 33);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (34, 'Lenguaje', 'ykogjmhmak', 34, 34);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (35, 'Educación Ciudadana', 'trwhlwsufx', 35, 35);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (36, 'Historia', 'wgihxvtpkq', 36, 36);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (37, 'Lenguaje', 'mkafngjnlk', 37, 37);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (38, 'Literatura', 'kzgkbpfjfz', 38, 38);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (39, 'Educación Física', 'ztyrjmipwu', 39, 39);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (40, 'Ciencias', 'tmzlfpbfku', 40, 40);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (41, 'Educación Física', 'skihhkmotr', 41, 41);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (42, 'Lenguaje', 'glnwlmnhby', 42, 42);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (43, 'Lenguaje', 'hbsmxibehm', 43, 43);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (44, 'Educación Física', 'xlshcfjmii', 44, 44);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (45, 'Inglés', 'lsuyxbzixo', 45, 45);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (46, 'Ciencias', 'pwdbbtrfyp', 46, 46);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (47, 'Historia', 'hoosejgmbd', 47, 47);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (48, 'Ciencias', 'lrfebeqznk', 48, 48);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (49, 'Tecnología', 'fmoeuhtvne', 49, 49);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (50, 'Lenguaje', 'tkfqinanux', 50, 50);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (51, 'Educación Artística', 'wczvfavgki', 51, 51);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (52, 'Ciencias', 'upcuxcmtgn', 52, 52);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (53, 'Tecnología', 'unomtrjsxs', 53, 53);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (54, 'Ciencias', 'nsvjdyzmcs', 54, 54);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (55, 'Educación Artística', 'cltdbldhhe', 55, 55);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (56, 'Inglés', 'pepixghnsq', 56, 56);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (57, 'Tecnología', 'fxkfxxamwp', 57, 57);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (58, 'Literatura', 'kfcvyxvtsf', 58, 58);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (59, 'Educación Física', 'evfobbegng', 59, 59);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (60, 'Educación Artística', 'cvbwgubxoh', 60, 60);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (61, 'Educación Ciudadana', 'gqsbqpqptk', 61, 61);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (62, 'Literatura', 'dfclqvzemn', 62, 62);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (63, 'Educación Artística', 'eemlfbrlkn', 63, 63);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (64, 'Ciencias', 'neahmxktuq', 64, 64);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (65, 'Ciencias', 'cucjlmafym', 65, 65);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (66, 'Ciencias', 'nzikyfpimu', 66, 66);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (67, 'Historia', 'dscjfgboar', 67, 67);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (68, 'Lenguaje', 'tocoqzppss', 68, 68);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (69, 'Matemáticas', 'zibskrenui', 69, 69);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (70, 'Tecnología', 'cgplyohzmd', 70, 70);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (71, 'Educación Artística', 'jrbleqseuq', 71, 71);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (72, 'Historia', 'ufcyqyfuay', 72, 72);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (73, 'Inglés', 'ifmvhhpzcs', 73, 73);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (74, 'Educación Artística', 'phkdyrtagi', 74, 74);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (75, 'Inglés', 'gsqfodojuh', 75, 75);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (76, 'Educación Artística', 'byfsrvxwyc', 76, 76);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (77, 'Inglés', 'jnsauxmznw', 77, 77);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (78, 'Inglés', 'dldszoftyt', 78, 78);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (79, 'Educación Física', 'ajkccqkakv', 79, 79);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (80, 'Historia', 'qwfzpvrlpj', 80, 80);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (81, 'Educación Física', 'vxlpqeqrsg', 81, 81);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (82, 'Literatura', 'dbfmpblwlv', 82, 82);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (83, 'Educación Física', 'fvxeuskmip', 83, 83);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (84, 'Inglés', 'lxhdffsenb', 84, 84);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (85, 'Ciencias', 'cmddkilgnw', 85, 85);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (86, 'Inglés', 'tvegizfsrx', 86, 86);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (87, 'Educación Física', 'cssmxxfqnh', 87, 87);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (88, 'Lenguaje', 'ndtkvzccgq', 88, 88);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (89, 'Tecnología', 'odtortyxsn', 89, 89);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (90, 'Educación Ciudadana', 'ibbcdksegx', 90, 90);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (91, 'Lenguaje', 'swohnotnke', 91, 91);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (92, 'Literatura', 'yfjxcrxtwo', 92, 92);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (93, 'Ciencias', 'okmanmmeys', 93, 93);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (94, 'Literatura', 'qapgziopvo', 94, 94);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (95, 'Educación Física', 'jyqvdfelkj', 95, 95);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (96, 'Educación Física', 'aqqlhiashs', 96, 96);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (97, 'Educación Artística', 'qzgskvikkj', 97, 97);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (98, 'Educación Ciudadana', 'fumqpemvtl', 98, 98);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (99, 'Educación Física', 'qjcrgafxrg', 99, 99);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (100, 'Educación Física', 'wxdzckpzvc', 100, 100);
