insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (1, 'Matemáticas 1', 'yqigpcpjcs', 1, 1);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (2, 'Literatura 1', 'sryxmipiiz', 2, 2);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (3, 'Ciencias 1', 'fpyieayhdb', 3, 3);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (4, 'Historia 1', 'dpoushvpab', 4, 4);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (5, 'Inglés 1', 'uyaaidkeul', 5, 5);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (6, 'Educación Física 1', 'xxqgiqlryh', 6, 6);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (7, 'Educación Artística 1', 'aclvicjvvp', 7, 7);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (8, 'Tecnología 1', 'uewdsxleki', 8, 8);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (9, 'Educación Ciudadana 1', 'bbpbtntcaj', 9, 9);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (10, 'Lenguaje 1', 'wgmjpxushg', 10, 10);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (11, 'Matemáticas 2', 'diraolluxl', 11, 11);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (12, 'Literatura 2', 'tncwhqhskz', 12, 12);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (13, 'Ciencias 2', 'ptttnueyht', 13, 13);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (14, 'Historia 2', 'xfvsotyfcj', 14, 14);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (15, 'Inglés 2', 'agkfhltphw', 15, 15);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (16, 'Educación Física 2', 'nuhgvluxxa', 16, 16);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (17, 'Educación Artística 2', 'sujskytfjd', 17, 17);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (18, 'Tecnología 2', 'sletjihzeo', 18, 18);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (19, 'Educación Ciudadana 2', 'qgijyondbq', 19, 19);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (20, 'Lenguaje 2', 'agpndvapri', 20, 20);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (21, 'Matemáticas 3', 'otyajljiwr', 21, 21);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (22, 'Literatura 3', 'elsowfhwqi', 22, 22);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (23, 'Ciencias 3', 'temxskpkax', 23, 23);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (24, 'Historia 3', 'zmzqlzisbp', 24, 24);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (25, 'Inglés 3', 'rknukqvrzr', 25, 25);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (26, 'Educación Física 3', 'fccwucdnoj', 26, 26);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (27, 'Educación Artística 3', 'fiwsxaoumb', 27, 27);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (28, 'Tecnología 3', 'dribgjtlsu', 28, 28);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (29, 'Educación Ciudadana 3', 'eftqyczaig', 29, 29);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (30, 'Lenguaje 3', 'kfcllwxmyd', 30, 30);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (31, 'Matemáticas 4', 'qkpsareowk', 31, 31);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (32, 'Literatura 4', 'iixwaanhjd', 32, 32);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (33, 'Ciencias 4', 'etzxyeqxez', 33, 33);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (34, 'Historia 4', 'ykogjmhmak', 34, 34);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (35, 'Inglés 4', 'trwhlwsufx', 35, 35);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (36, 'Educación Física 4', 'wgihxvtpkq', 36, 36);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (37, 'Educación Artística 4', 'mkafngjnlk', 37, 37);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (38, 'Tecnología 4', 'kzgkbpfjfz', 38, 38);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (39, 'Educación Ciudadana 4', 'ztyrjmipwu', 39, 39);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (40, 'Lenguaje 4', 'tmzlfpbfku', 40, 40);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (41, 'Matemáticas 5', 'skihhkmotr', 41, 41);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (42, 'Literatura 5', 'glnwlmnhby', 42, 42);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (43, 'Ciencias 5', 'hbsmxibehm', 43, 43);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (44, 'Historia 5', 'xlshcfjmii', 44, 44);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (45, 'Inglés 5', 'lsuyxbzixo', 45, 45);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (46, 'Educación Física 5', 'pwdbbtrfyp', 46, 46);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (47, 'Educación Artística 5', 'hoosejgmbd', 47, 47);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (48, 'Tecnología 5', 'lrfebeqznk', 48, 48);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (49, 'Educación Ciudadana 5', 'fmoeuhtvne', 49, 49);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (50, 'Lenguaje 5', 'tkfqinanux', 50, 50);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (51, 'Matemáticas 6', 'wczvfavgki', 51, 51);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (52, 'Literatura 6', 'upcuxcmtgn', 52, 52);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (53, 'Ciencias 6', 'unomtrjsxs', 53, 53);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (54, 'Historia 6', 'nsvjdyzmcs', 54, 54);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (55, 'Inglés 6', 'cltdbldhhe', 55, 55);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (56, 'Educación Física 6', 'pepixghnsq', 56, 56);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (57, 'Educación Artística 6', 'fxkfxxamwp', 57, 57);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (58, 'Tecnología 6', 'kfcvyxvtsf', 58, 58);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (59, 'Educación Ciudadana 6', 'evfobbegng', 59, 59);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (60, 'Lenguaje 6', 'cvbwgubxoh', 60, 60);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (61, 'Matemáticas 7', 'gqsbqpqptk', 61, 61);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (62, 'Literatura 7', 'dfclqvzemn', 62, 62);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (63, 'Ciencias 7', 'eemlfbrlkn', 63, 63);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (64, 'Historia 7', 'neahmxktuq', 64, 64);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (65, 'Inglés 7', 'cucjlmafym', 65, 65);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (66, 'Educación Física 7', 'nzikyfpimu', 66, 66);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (67, 'Educación Artística 7', 'dscjfgboar', 67, 67);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (68, 'Tecnología 7', 'tocoqzppss', 68, 68);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (69, 'Educación Ciudadana 7', 'zibskrenui', 69, 69);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (70, 'Lenguaje 7', 'cgplyohzmd', 70, 70);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (71, 'Matemáticas 8', 'jrbleqseuq', 71, 71);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (72, 'Literatura 8', 'ufcyqyfuay', 72, 72);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (73, 'Ciencias 8', 'ifmvhhpzcs', 73, 73);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (74, 'Historia 8', 'phkdyrtagi', 74, 74);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (75, 'Inglés 8', 'gsqfodojuh', 75, 75);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (76, 'Educación Física 8', 'byfsrvxwyc', 76, 76);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (77, 'Educación Artística 8', 'jnsauxmznw', 77, 77);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (78, 'Tecnología 8', 'dldszoftyt', 78, 78);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (79, 'Educación Ciudadana 8', 'ajkccqkakv', 79, 79);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (80, 'Lenguaje 8', 'qwfzpvrlpj', 80, 80);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (81, 'Matemáticas 9', 'vxlpqeqrsg', 81, 81);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (82, 'Literatura 9', 'dbfmpblwlv', 82, 82);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (83, 'Ciencias 9', 'fvxeuskmip', 83, 83);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (84, 'Historia 9', 'lxhdffsenb', 84, 84);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (85, 'Inglés 9', 'cmddkilgnw', 85, 85);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (86, 'Educación Física 9', 'tvegizfsrx', 86, 86);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (87, 'Educación Artística 9', 'cssmxxfqnh', 87, 87);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (88, 'Tecnología 9', 'ndtkvzccgq', 88, 88);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (89, 'Educación Ciudadana 9', 'odtortyxsn', 89, 89);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (90, 'Lenguaje 9', 'ibbcdksegx', 90, 90);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (91, 'Matemáticas 10', 'swohnotnke', 91, 91);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (92, 'Literatura 10', 'yfjxcrxtwo', 92, 92);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (93, 'Ciencias 10', 'okmanmmeys', 93, 93);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (94, 'Historia 10', 'qapgziopvo', 94, 94);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (95, 'Inglés 10', 'jyqvdfelkj', 95, 95);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (96, 'Educación Física 10', 'aqqlhiashs', 96, 96);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (97, 'Educación Artística 10', 'qzgskvikkj', 97, 97);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (98, 'Tecnología 10', 'fumqpemvtl', 98, 98);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (99, 'Educación Ciudadana 10', 'qjcrgafxrg', 99, 99);
insert into MATERIA (expediente, nombre, descripcion, expediente_profesor, expediente_curso) values (100, 'Lenguaje 10', 'wxdzckpzvc', 100, 100);
